service: sls-project

plugins:
  - serverless-esbuild
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x

functions:
  hello:
    handler: ./src/handler.hello
    events:
      - httpApi:
          path: /
          method: GET
