service: sls-project

plugins:
  - serverless-esbuild
  - serverless-dynamodb
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  tableName: sls-project-table
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: offline/migrations

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  environment:
    tableName: ${env:TABLE_NAME}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource:
        - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.tableName}"
        - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.tableName}/index/EmailIndex"

useDotenv: true

functions:
  proxy:
    handler: src/index.handler
    events:
      - httpApi: ANY /{proxy+}

resources:
  Resources:
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
          -
            AttributeName: email
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          -
            IndexName: EmailIndex
            KeySchema:
              -
                AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
